### ISSUE TITLE
4.0

### ISSUE THREAD

**Issue by AndriyOrlov** [bblanimation/interactive-physics-editor#14]
Traceback (most recent call last):
  File "D:\Blender\stable\blender-4.0.2+stable.9be62e85b727\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "D:\Blender\stable\blender-4.0.2+stable.9be62e85b727\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'interactive-physics-editor-1'

**Comment by PhiMue86** [comment]
This happens because the plugin's folder contains the full stop/period character in the version number, which is not allowed. If you remove the version number from the folder, you should be able to enable it. However, I cannot get it to work (in Blender 3.6), anyway, with the same error that's reported here: https://github.com/bblanimation/interactive-physics-editor/issues/13

**Comment by AndriyOrlov** [comment]
yes replacing the dots helped but still won't work this addon is really cool and wouldn't want to miss out on using it


Description of the Problem:

Blender Version: 004.001.000
Addon Version: 1, 1, 6
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.22631-SP0
   version  = 10.0.22631
   python   = 3.11.7
Error:
EXCEPTION (<class 'TypeError'>): bpy_struct: item.attr = val: expected a string enum, not _PropertyDeferred
         C:\Users\Andre\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\interactive-physics-editor-116\operators\setup_and_run_ipe.py
000 0208:set_up_physics() rb.collision_shape = scn.physics.collision_shape
001 0106:execute() self.set_up_physics()
