### ISSUE TITLE
Error(s) on exiting

### ISSUE THREAD

**Issue by MarkHolley** [bblanimation/interactive-physics-editor#7]
Good day,

I purchased this on Blender Market a while ago and have enjoyed using it. I've been getting errors since I first installed it - I don't know if those errors are my fault or possible problems with the scripting. I'm currently using Blender 2.8 RC2 and version 1.1.1 of the script.

The error messages follow:

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "C:\Users\markh\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\interactive_physics_editor_1_1_1\operators\setup_phys.py", line 80, in modal
    self.close_interactive_sim()
  File "C:\Users\markh\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\interactive_physics_editor_1_1_1\operators\setup_phys.py", line 184, in close_interactive_sim
    self.sim_scene.frame_set(self.orig_frame)
ReferenceError: StructRNA of type Scene has been removed

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\markh\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\interactive_physics_editor_1_1_1\lib\reportError.py", line 44, in execute
    libraryServersPath = os.path.join(getLibraryPath(), "error_log", self.txt_name)
NameError: name 'getLibraryPath' is not defined
```

**Comment by bblanimation** [comment]
Hi Mark,

Thank you for reporting this bug! The issue has been fixed for v1.1.2, the next release of the Interactive Physics Editor. Expect it soon after Blender 2.80 is officially released!

-Christopher
